# These settings were created and optimized by https://github.com/henrique-coder, for the ruff software (https://github.com/astral-sh/ruff).
# Put this file (ruff.toml) in your project root folder and run `ruff check` or `ruff format` (make sure to run `pip install -U ruff` first).

include = ["*.py"]
exclude = [".idea", ".venv", "__pycache__", ".ruff_cache"]
target-version = "py313"
line-length = 130
indent-width = 4

[lint]
fixable = ["ALL"]
unfixable = []
select = ["E4", "E7", "E9", "F", "UP", "B", "SIM"]
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[lint.pydocstyle]
convention = "google"

[lint.flake8-quotes]
docstring-quotes = "double"

[format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = true
line-ending = "auto"
docstring-code-format = true
